### ISSUE TITLE
How to use full convolutional neural network?

### ISSUE THREAD

**Issue by Huer-H** [Vanka0051/speech_enhancement#1]
Hello, is it convenient for you to share the steps of using your code file？

**Comment by JH2018-2021** [comment]
您能更新下代码使用上的一些介绍吗？

**Comment by Huer-H** [comment]
您好，您的main_crn模型中同时传入tfrecords文件，以及两个data.h5文件，其中rfrecords文件是用来进行训练的，那么这两个data.h5文件是用来做什么的呢？
您方便回复下我的疑问吗？

**Comment by Huer-H** [comment]
Hello, in your main_crn model, both the tfrecords file and two data.h5 files are passed in, among which the rfrecords file is used for training, so what are these two data.h5 files used for?Could you please reply to my question?
